### ISSUE TITLE
Rust syntax highlighting broke

### ISSUE THREAD

**Issue by Speak2Erase** [catppuccin/vscode#153]
Before:
![image](https://github.com/catppuccin/vscode/assets/54482069/2b31ffcb-6a36-4a67-9131-22e7708f652d)
After:
![image](https://github.com/catppuccin/vscode/assets/54482069/e1f278f0-4871-410f-a192-5dc41d748d1a)

Everything looks closer to when I have rust-analyzer disabled:
![image](https://github.com/catppuccin/vscode/assets/54482069/d54f87bb-3306-49dd-bdab-093ef724cd2c)

I honestly really liked the old styling because not many themes had the amount of clarity catppuccin did. If there was some way to get a mix of the old behavior as well as the new styling, that would be awesome!

**Comment by nekowinston** [comment]
Please see https://github.com/catppuccin/vscode/issues/62, these changes were all intentional, and offering two entirely different syntax styles (2.x/3.) would make maintaining this theme extremely difficult. 

I just added Chromatic UI testing (https://github.com/catppuccin/vscode/pull/154) to ensure that any future syntax changes in 3.x will not cause unforeseen changes; so I'm committed to make 3.x, and it's style, the best version of this extension.

If you're still happier with the old theme, you can always install an older version from the marketplace:
![vscode 'install another version'](https://user-images.githubusercontent.com/79978224/265532186-af6c581a-3450-48b9-932b-52b8a528aeb7.png)
