### ISSUE TITLE
Vivid color

### ISSUE THREAD

**Issue by QuentinVdr** [catppuccin/vscode#177]
Can we get an option to brighter semantic colours ?

**Comment by nekowinston** [comment]
Hey, I delayed work on this PR because I don't think our theme would currently benefit from highlighting semantic colors separately. If you want to try how it *would look*, you can download the PR build for #210 -> [here](https://github.com/catppuccin/vscode/actions/runs/6698591796?pr=210), then set `catppuccin.underlinedSemanticTokens` to `true` in your settings.

![2023-10-30-215652@2x](https://github.com/catppuccin/vscode/assets/79978224/4125da2d-397b-41f3-8ff0-b8f6d1f3d7ad)

I went with `underline` for now, since it's super visible, and it shows what would get highlighted; it isn't much, and I don't think it conveys any particularly useful info to the user - that might be super subjective, though.
I'd appreciate it if you can give it a try.
