### ISSUE TITLE
Godot GDScript Lacking Syntax Highlighting

### ISSUE THREAD

**Issue by dannymate** [catppuccin/vscode#187]
Would it be possible to add GDScript support for syntax highlighting? You can see super() and methods calls aren't coloured.
![image](https://github.com/catppuccin/vscode/assets/26135914/9bd45776-f045-42cf-b530-98b0a9ce159a)

If there's any information required let me know I'm not sure what you'd need.

**Comment by dannymate** [comment]
There's a grammer reference [here](https://docs.godotengine.org/en/stable/contributing/development/file_formats/gdscript_grammar.html). Maybe it'll be useful.

**Comment by kkrypt0nn** [comment]
The issue here seems to be more with the extension, which needs to be installed, which doesn't recognize some special keywords.

For example with the `super()` calls, it recognizes them as `function.any-method`
![image](https://github.com/catppuccin/vscode/assets/43011723/b709290f-1325-4d88-9cee-3dd2c5b54b4e)
which in my opinion clearly isn't. It's not a function/method like any others.

About method calls, they shouldn't be colored according to the syntax highlighting of the website:
![image](https://github.com/catppuccin/vscode/assets/43011723/ea995402-5715-4387-a856-cf9f18c42601)
![image](https://github.com/catppuccin/vscode/assets/43011723/35cad86e-774f-4322-a227-12f1e28b57da)
![image](https://github.com/catppuccin/vscode/assets/43011723/612e6ed5-50b3-4abd-9114-d46b5e0c7b39)

**Comment by dannymate** [comment]
Ah ok. Thanks for getting back to me. This doesn't seem to be an issue with the theme then. I'll close this now.
