### ISSUE TITLE
[JavaScript] Syntax highlight issues

### ISSUE THREAD

**Issue by LatenPath** [catppuccin/vscode#199]
1. Arguments in JSDoc need highlight:
```
class Cat {
  /**
   * Constructs a new instance of the class.
   *
   * @param {string} name - The name of the object.
   * @param {number} age - The age of the object.
   */
  constructor (name, age) {
    this.name = name;
    this.age = age;
  }
}
```
![image](https://github.com/catppuccin/vscode/assets/145383056/1ee35a95-58cb-496f-9431-bdd8cc5ade95)

"name" and "age" in JSDoc above should be highlighted with color light arguments in <constructor>.

2. Variable in string with "this.<var>" missing highlight:
```
 sleep () {
    console.log(`${this.name} is sleeping...`);
  }
  
//
  
const tom = new Cat('Tom', 5);
console.log(`[INFO] - test.js:27 - tom: ${tom}`);
```
![image](https://github.com/catppuccin/vscode/assets/145383056/e9f8a349-177d-4fea-8bcc-b21d132c85ea)

"${this.name}" missing highlighted bracket like the one below.

FIXED: I change bracket mode to Neovim and that one changed color. But the color a litte different:
![image](https://github.com/catppuccin/vscode/assets/145383056/f6389fdd-c2fc-4e71-af91-1e3797d2593c)
![image](https://github.com/catppuccin/vscode/assets/145383056/dd46b7be-bba8-4c71-a1b3-48e4c4b45a18)

3.  Class variable highlight.
<Toggle on/off in setting for personal need>
```
const tom = new Cat('Tom', 5);
console.log(`[INFO] - test.js:27 - tom: ${tom}`);
tom.sleep();

let a = 10;
a = 5;
console.log(`[INFO] - test.js:32 - a: ${a}`);
```
![image](https://github.com/catppuccin/vscode/assets/145383056/31dea2aa-477a-4068-82eb-1abd86c315d9)

![image](https://github.com/catppuccin/vscode/assets/145383056/d81cb83f-d5c7-4aca-bc3b-0674dcb3d36b)

It make "tom.name" lack of highlight and hard to specific.

In "Monokai", "Darcula",... theme, a class variable will be highlight with different color from normal var. The one in Darcula theme:
![image](https://github.com/catppuccin/vscode/assets/145383056/c4eb8fba-0315-4854-b74c-1d37c75aef40)

4. Can we have some changes in color of "console", "this" and argument?... My eyes not so good, sometimes i cant see different between them, it make me a little confuse...
![image](https://github.com/catppuccin/vscode/assets/145383056/e415b340-88d8-42b7-a5ed-14d8a1c50f2c)

5. "new",.. keyword maybe should be Bold for different.
![image](https://github.com/catppuccin/vscode/assets/145383056/597dcf02-98d8-401a-992e-bede6b1e6f2a)

THANK YOU ALL SO MUCH FOR THIS FANTASTIC THEME. That is what i'm looking for for a long time, and now it just lack small things left <3

**Comment by nekowinston** [comment]
Hey, thanks for the kinds words and the detailed issue 🙂 

1.) I'll push a fix for that shortly, good catch.

2.) That sometimes happens with the rainbow brackets feature, as you noted. Since `green` is a color in the rainbow, enough indents will lead to green appearing in `${}`-style string interpolation.
I added the `dimmed` setting to have the same rainbow, but distinguishable from normal rainbow colors, for exactly that reason.

3.) This is a limitation of VSCode and its semantic tokens, Dracula doesn't treat class instances any different - it merely appears this way in your example:
![2023-10-29-190843@2x](https://github.com/catppuccin/vscode/assets/79978224/3b16d117-e7a9-4da5-a829-1785760af9da)
![2023-10-29-190854@2x](https://github.com/catppuccin/vscode/assets/79978224/d4b8faa3-5ee7-49af-8231-cba175996229)

`tom` is highlighted as a const, while `foo` is a readwrite variable.

4.) This change would impact the style of other editors/languages, so if you want them for your own readability, please add
```json
  "editor.semanticTokenColorCustomizations": {
    "[Catppuccin Mocha]": {
      "rules": {
        "variable.defaultLibrary": {
          "foreground": "#f5c2e7"
        }
      }
    }
  }
```
or similar to your VSCode settings JSON.

5.) I haven't spent any time on the **bold keywords** since the 3.0.0 release, I will need to reconsider those completely. I don't think I've highlighted anything as **bold** in the latest release, `new` certainly would be a good canditate for bold highlights. 🙂

**Comment by LatenPath** [comment]
Your quick support is so great SIR! I have succesfully change "this." and "console." keyword color (change "variable.language.this.js" in "textMateRules" for "this." if someone need). 
Now I just have a few questions left about my number-"3" issue:
![image](https://github.com/catppuccin/vscode/assets/145383056/b83f6f83-07b3-4b62-9981-b8301b6706bc)
As you can see, the highlight of "tom.name" make me a litlte confused. So I think we should change the part ".name" color for different from the variable name. So then we can differentiate the two of them :D

**Comment by nekowinston** [comment]
The JSDoc highlight fixes & bold keyword support are live now.
