### ISSUE TITLE
Typescript types have wrong colors inside nested `[]`.

### ISSUE THREAD

**Issue by GustavoFenilli** [catppuccin/vscode#203]
If you look at this line: `(...args: [...GlobalEventsMap[K]['parameters'], ...A]) => GlobalEventsMap[K]['result'];`, the `[K]['parameters']` should be the same color as `[K]['result']`.

![image](https://github.com/catppuccin/vscode/assets/14954720/8f4c0686-b00c-4c7b-814f-1bb9799126b4)

**Comment by nekowinston** [comment]
I took a look at this, and I'm not really sure what you mean; do you mean the *brackets* themselves?
![2023-10-30-111039@2x](https://github.com/catppuccin/vscode/assets/79978224/de64f278-0506-4d3e-aedd-ab9d28239850)
This screenshot is with the config set to `"editor.bracketPairColorization.enabled": false`.
The `[K]['parameters']` with it turned on is green because it is nested inside an additional pair of parentheses.

**Comment by GustavoFenilli** [comment]
I see so because it is `[[K]['parameters']]` it makes it green? it still looks odd right?

I would expect the `[` and `]` to not be green like a string tho.

**Comment by nekowinston** [comment]
I cannot control the colors of brackets, parentheses and braces, if the user has `editor.bracketPairColorization` enabled.
That's why you have the option of turning it off completely, or selecting other styles like `dimmed`:
![2023-10-30-151519@2x](https://github.com/catppuccin/vscode/assets/79978224/90346fb1-a626-40da-80f3-3639be34cd3e)

![2023-10-30-151458@2x](https://github.com/catppuccin/vscode/assets/79978224/14bf3279-4399-4898-99e5-27b20d3fbc3c)

**Comment by GustavoFenilli** [comment]
Oh I see what you mean now, thanks for the explanation.
