### ISSUE TITLE
[Feature request]Update ctp to 0.2.0

### ISSUE THREAD

**Issue by LC0117** [catppuccin/vscode#23]
Could we have a 0.2.0 bump? It' really nice as ctp-0.2.0 has a light theme.

**Comment by KiligFei** [comment]
+1

**Comment by camblomquist** [comment]
There's now a minimal port to 0.2.0 on the dev branch. There's a few scuffed up parts of it (I heard latte in particular isn't quite right,) but it's available if you want to test it. If you find any issues while using it, be sure to share so that they can be fixed.

**Comment by LC0117** [comment]
@camblomquist Thanks for the effort!
I have tried the theme, and I found that the latte theme has kinda too much red hue.

## Shot with catppuccin/nvim
<img width="1440" alt="截屏2022-06-13 11 31 49" src="https://user-images.githubusercontent.com/77481149/173274761-11db8223-261c-429b-be77-5608715d2905.png">

## Shot with catppuccin/vscode:dev
<img width="1440" alt="截屏2022-06-13 11 33 19" src="https://user-images.githubusercontent.com/77481149/173274921-39b33fd6-de60-47e0-8b0a-f0261ee57ba3.png">

**Comment by camblomquist** [comment]
@LC0117 Before taking the minimal approach to the update, I had looked into trying to match nvim's 0.2.0 release as previous contributors appear to have done before. But I found difficulty in this task as the tokens that VSCode can color are very different from what nvim does, at least when looking at the nvim theme. I agree that it's too red, but I would imagine that this implies a greater issue with the color selection as a whole rather than just with the latte theme.

**Comment by LC0117** [comment]
>  I agree that it's too red, but I would imagine that this implies a greater issue with the color selection as a whole rather than just with the latte theme.

Yes, I agree. Because the same palette in catppuccin_mocha looks fine.

<img width="1552" alt="截屏2022-06-15 00 26 20" src="https://user-images.githubusercontent.com/77481149/173628219-e69f021a-f6be-4a2e-92c6-6680ba08731a.png">

**Comment by lvignoli** [comment]
Hi, any progress on this port?

**Comment by nekowinston** [comment]
Closed with 287785ab92c5c235dae76b93f877243b579e0828.
We're working on getting it to the VSCode Marketplace.
