### ISSUE TITLE
Message in settings.json

### ISSUE THREAD

**Issue by ale-dg** [catppuccin/vscode#241]
Hi, 

Not sure why I am getting this message. I changed a colour in the settings.json for my preference and I am being displayed this warning:

`
Problems loading reference 'https://cdn.jsdelivr.net/gh/catppuccin/vscode@v3.8.1/schemas/colorOverrides.schema.json': Unable to load schema from 'https://cdn.jsdelivr.net/gh/catppuccin/vscode@v3.8.1/schemas/colorOverrides.schema.json': getaddrinfo ENOTFOUND cdn.jsdelivr.net.
`

So far it has not made something go wrong, but I'd rather report now before something happens down the road...

Thanks

Best

**Comment by nekowinston** [comment]
Please see #197, #213. This happens when your network or firewall blocks that URL.

I already changed it from githubusercontent to jsdelivr for Indian users. Maybe [this esm.sh url I linked](https://github.com/catppuccin/vscode/issues/213#issuecomment-1822406101) works? I didn't get a response from @Eshanatnight.

**Comment by ale-dg** [comment]
That is weird though, as I am not located anywhere near India... I have just opened my computer again and the message is gone. Maybe it was something related to the reload of the theme due to the update you released recently.

I am closing the issue. Thanks for the help.

Best
