### ISSUE TITLE
3.11.0 does not adhere to accent color or custom UI color overrides

### ISSUE THREAD

**Issue by alexchantastic** [catppuccin/vscode#291]
After upgrading to 3.11.0 via the VSCode Marketplace, my accent color and custom UI color settings are no longer applying. Downgrading to 3.10.1 fixes the issue.

**Comment by nekowinston** [comment]
Thanks for reporting this, but I have trouble reproducing it.
Could you please upgrade to 3.11.0 and post your vscode startup logs?
```command
code --verbose "$(mktemp -d)" > vscode.log 2>&1
```
and close VSCode as soon as it opened the empty directory.

I'd try deleting the catppuccin-vsc directories, since the cache occasionally leads to odd behavior, e.g.
```command
rm -rf ~/.vscode/extensions/catppuccin.catppuccin-vsc-*
```
(double check that this is your vscode extensions dir

**Comment by alexchantastic** [comment]
Deleting the catppuccin-vsc directories and reinstalling the 3.11.0 extension seems to have worked! Thanks for your help 😃.
