### ISSUE TITLE
Problems loading reference: Invalid URL. The URL structure is /gh/user/repo@version/file.js.(768)

### ISSUE THREAD

**Issue by tommdq** [catppuccin/vscode#416]
I'm getting the following error when the extension is enabled: 

Problems loading reference 'https://cdn.jsdelivr.net/gh/catppuccin/vscode@catppuccin-vsc-v3.15.0/packages/catppuccin-vsc/schemas/customUIColors.schema.json': Unable to load schema from 'https://cdn.jsdelivr.net/gh/catppuccin/vscode@catppuccin-vsc-v3.15.0/packages/catppuccin-vsc/schemas/customUIColors.schema.json': Bad request. The request cannot be fulfilled due to bad syntax.
Invalid URL. The URL structure is /gh/user/repo@version/file.js.(768)

The error goes away after disabling the extension

**Comment by sgoudham** [comment]
Hey 👋,

I know we've previously had these type of errors (https://github.com/catppuccin/vscode/issues/241#issuecomment-1843460505) but the message doesn't seem that relevant to the previous issues.

Can you check if you get the same on a earlier version of the package like 3.14.0?

Thanks!

**Comment by tommdq** [comment]
Hi! Thanks for replying.. I tried changing version to 3.14.0 but still getting the same error: 

```
Problems loading reference 'https://cdn.jsdelivr.net/gh/catppuccin/vscode@catppuccin-vsc-v3.14.0/packages/catppuccin-vsc/schemas/customUIColors.schema.json': Unable to load schema from 'https://cdn.jsdelivr.net/gh/catppuccin/vscode@catppuccin-vsc-v3.14.0/packages/catppuccin-vsc/schemas/customUIColors.schema.json': Bad request. The request cannot be fulfilled due to bad syntax.
Invalid URL. The URL structure is /gh/user/repo@version/file.js.(768)
```

**Comment by clearbluesky777** [comment]
i have the same error msg it happend when i update vs code to 1.92.0

**Comment by sgoudham** [comment]
I can confirm that I'm able to reproduce after updating VSCode to v1.92.0.

I'm inclined to believe it may be an upstream issue since the CDN URL hasn't changed and the structure in the error seems to match.

**Comment by sgoudham** [comment]
While investigating this issue, I came across this section in the [Contribution Points](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) of the VSCode Reference:

![image](https://github.com/user-attachments/assets/166795b1-f04d-4d50-93a6-f72f30b827a9)

I'm not sure when this section was added but it seems like our current method of using `$ref` was never encouraged or as of the new update, explicitly discouraged. 

https://github.com/catppuccin/vscode/blob/f0daac51ddc194a3d91ec07277bd79c6168870f5/packages/catppuccin-vsc/package.json#L73-L84

I'm still a bit confused as the error seems to be trying to parse the URL but that may be a fallback error due to VSCode not supporting `$ref` as stated in the documentation.

I think a solution to this would be to inline the schema into the `package.json` instead of referencing via `$ref`.

**Comment by sgoudham** [comment]
Investigated a bit more with the help of @nekowinston, we think it's due to an [upstream commit](https://github.com/microsoft/vscode/commit/3be49eccc5fc69684e5073285e21548cc4da24aa) that's changed some of the inner workings of schema retrieval.

With regards to a workaround, using `esm.sh` works fine locally so that should fix this error.

**Comment by Wire518** [comment]
ADE
