### ISSUE TITLE
Newest release has broken custom inlayHint setup

### ISSUE THREAD

**Issue by janriemer** [catppuccin/vscode#88]
Hi :wave: 
it seems that **custom inlay hint** setup is broken with the newest release. :cry: 

I've seen the following [recent change](032dc3) (032dc31) that seems to add default styles for catppuccin (issue #83, PR #87).
I assume that this has somehow broken my custom setup. :crying_cat_face: 

Also, it seems that it doesn't even use the new default styles (see screenshot below).

### Custom setup
```
"workbench.colorCustomizations": {
        "[Catppuccin Macchiato]": {
            "editorInlayHint.foreground": "#74416b",
            "editorInlayHint.background": "#41363f2f",
        }
    },
```
### Before
<a href="https://ibb.co/pny94Wk"><img src="https://i.ibb.co/b7J8NHG/catppuccin-inlay-working.jpg" alt="catppuccin-inlay-working" border="0" /></a>

### After (broken):
<a href="https://ibb.co/KLWMgt6"><img src="https://i.ibb.co/3McDbx1/vscode-no-inline-Hint.jpg" alt="vscode-no-inline-Hint" border="0" /></a>

### VS Code version
1.74.3

### Catppuccin version:
2.6.0
#### Theme:
Catppuccin Macchiato

**Comment by nekowinston** [comment]
Hi :wave:

Thanks for the detailed write-up, it helped with finding the root cause faster.

Previously, we didn't style inlay hints *at all*, and it turns out that VSCode uses 3 kinds of inlay hints:
`editorInlayHint.foreground`, `editorInlayHint.typeForeground`, and `editorInlayHint.parameterForeground` (plus their respective backgrounds).

So if you'd like to use your customization, you'd have to include those other types, since we're styling them since yesterday:
```json
  "workbench.colorCustomizations": {
    "[Catppuccin Macchiato]": {
      "editorInlayHint.foreground": "#74416b",
      "editorInlayHint.background": "#41363f2f",
      "editorInlayHint.typeForeground": "#74416b",
      "editorInlayHint.typeBackground": "#41363f2f",
      "editorInlayHint.parameterForeground": "#74416b",
      "editorInlayHint.parameterBackground": "#41363f2f",
    }
  },
  ```

**Comment by janriemer** [comment]
Ah, thank you for your swift response, this works like a charm! :sparkles: 

Also, thank you for putting the exact solution (with my colors!) in here - I just needed to copy-paste and it worked. :heart: :hugs: 

### Possible improvements
I'm wondering, though, whether we can detect, if `editorInlayHint.foreground` or `.background` is already set and if so, to __not__ set `type` and `parameter` colors. I think the current behaviour is quite unexpected (although admittedly "_technically correct_", because if `type` and `parameter` values are not present, well, you set them to the default catppuccin values).   

What do you think?

------------------------------

For now, I'm closing this, because the problem has been solved with your suggestion. Thanks again. :slightly_smiling_face:

**Comment by nekowinston** [comment]
Glad this fixes it for you!

The following screenshot shows the current styling for our inlay hints:
![image](https://user-images.githubusercontent.com/79978224/215343412-9d958c9d-c7c1-40e7-a540-2adfb030926e.png)

`let result: Vec<u8>` is `type`
`String::from_utf8(vec: result)` is the `parameter`
`fn convert_vector` is the previous catch-all & non-scoped `editorInlayHint.*`

We discussed this in Discord yesterday, and decided on this logic: 
There is subtle shading applied, since for `type`, you'd have the most restrictions, `parameter` is important info but less restricted. The non-scoped one would be fine to look like a comment.

I talked to @sgoudham about it, since we're using the same logic in [catppuccin/jetbrains](https://github.com/catppuccin/jetbrains).

**Comment by janriemer** [comment]
@nekowinston IMHO, the inlay hints for `type` and `parameter` should set themselves more apart from the rest of the code, by being much more desaturated. I only want to see it if I focus on those inlay hints with my eyes.
But maybe that's just me. 😉 

What do you think about the following (see my post above - if your previous answer has already covered this, my apologies, but I think it hasn't):
> I'm wondering, though, whether we can detect, if editorInlayHint.foreground or .background is already set and if so, to not set type and parameter colors. I think the current behaviour is quite unexpected (although admittedly "technically correct", because if type and parameter values are not present, well, you set them to the default catppuccin values).

Is something like this possible?
